services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: minecraft-server
    ports:
      - "25565:25565"   # Minecraft
      - "25575:25575"   # RCON (para watchdog)
    environment:
      EULA: "TRUE"
      VERSION: "1.21.11"
      TYPE: "PAPER"

      MEMORY: ${MEMORY:-4G}
      USE_AIKAR_FLAGS: "true"
      DIFFICULTY: "hard"
      
      HARDCORE: "false"
      MAX_PLAYERS: "8"
      VIEW_DISTANCE: "12"
      SPAWN_PROTECTION: "0"
      PVP: "true"
      ALLOW_NETHER: "true"
      GENERATE_STRUCTURES: "true"
      
      MOTD: "§6⚔ §lHardcore Survival §6⚔\n§7¡Bienvenido al desafío!"
      
      WHITELIST: ${WHITELIST:-false}
      OPS: ${OPS_PLAYER:-}
      ENFORCE_WHITELIST: "true"

      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD:-minecraft}
      RCON_PORT: "25575"

      LEVEL: "world"
      SEED: ${WORLD_SEED:-}
      MAX_WORLD_SIZE: "29999984"

    volumes:
      - ./data:/data
    restart: unless-stopped
    stdin_open: true
    tty: true
